# basic options
title: Pharma Dashbord
author: Ezzedine Fitouri
email: ezzedinefitouri@gmail.com
description: A wonderful site
Linkedin: https://www.linkedin.com/in/ezzedine-marketing
github_username:  EzzedineFitouri

# Build settings
markdown: kramdown
theme: minima
